---
title: "Example DMS Plans"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: spacelab
    social: menu
    navbar:
      - { title: "About", href: "https://osf.io/uadxr/wiki/Example%20DMSP%20Plans/", align: left }
      - { title: "Working Group on NIH DMSP Guidance", href: "https://osf.io/uadxr/wiki/home/", align: left }
    css: custom.css
    source_code: https://github.com/example-DMS-plans/examples/blob/main/index.Rmd
---

```{r setup, include = FALSE}
library(tidyverse)
library(lubridate)
library(DT)

source("data_functions.R")

if (!file.exists("plans_data.RDS"))
{
    # grab data from google sheets
    download_raw_data()
    
    # read in raw data, process and save out
    plans_data <- process_raw_data()
    saveRDS(plans_data, "plans_data.RDS")
}

plans <- readRDS("plans_data.RDS")
```

```{r process data, include = FALSE}
plans <- plans %>%
    mutate_at("Date", parse_date_time, c("mdy", "y")) %>%
    mutate_at("Date", as.Date)
```

The example DMP directory was compiled from researchers, institutions, libraries and workgroups who shared their data management plans online from 2012-2022.<br />
This directory is intended to help researchers comply with the new NIH policy and will not be updated after publishing.

```{r}
plans %>%
    datatable(rownames = FALSE, 
              options = list(pageLength = NROW(plans), 
                             scrollY = "800px", 
                             columnDefs = list(list(
                                 targets = 6,
                                 render = JS(
                                     "function(data, type, row, meta) {",
                                     "if (type === 'display') {",
                                     "data = '<a href=\"' + data + '\">' + 'link' + '</a>';",
                                     "}", 
                                     "return data;", 
                                     "}")
                             )))
    )
```
